switch to 3.5-slim from 3.5-alpine
- now that I have introduced PIL, I was getting the following
error with 3.5-alpine, which I don't get if I used 3.5-slim

    Traceback (most recent call last):
      File "/app/server.py", line 4, in <module>
        from precomputed_lookup_splitter import PreComputedLookupSplitter
      File "/app/precomputed_lookup_splitter.py", line 5, in <module>
        from schema import Piece, BitmapImage, Place, SpriteOffset, Sprite
      File "/app/schema.py", line 5, in <module>
        from PIL import Image
      File "/app/PIL/Image.py", line 58, in <module>
        from . import _imaging as core
    ImportError: Error relocating /app/PIL/.libs/libz-a147dcb0.so.1.2.3: __fprintf_chk: symbol not found